#ifndef MATCH_STATE_KEYS_H
#define MATCH_STATE_KEYS_H

#define MATCH_STATE_KEY_TIME "time"
#define MATCH_STATE_KEY_ROUND "round"
#define MATCH_STATE_KEY_TURN "turn"
#define MATCH_STATE_KEY_STATE "state"
#define MATCH_STATE_KEY_OVERTIME_ACTIVE "otActive"
#define MATCH_STATE_KEY_OVERTIME_START "otStart"
#define MATCH_STATE_KEY_OVERTIME_END "otEnd"
#define MATCH_STATE_KEY_OVERTIME_COUNT "otCount"
#define MATCH_STATE_KEY_OVERTIME_LENGTH "otLength"
#define MATCH_STATE_KEY_TIMEOUT_ACTIVE "toActive"
#define MATCH_STATE_KEY_TIMEOUT_TEAM "toTeam"
#define MATCH_STATE_KEY_TIMEOUT_EXPIRE "toExpire"
#define MATCH_STATE_KEY_TIMEOUT_OWNER "toOwner"
#define MATCH_STATE_KEY_TIMEOUT_RED "toRed"
#define MATCH_STATE_KEY_TIMEOUT_BLUE "toBlue"
#define MATCH_STATE_KEY_TIMEOUT_LENGTH "toLength"
#define MATCH_STATE_KEY_TIMEOUT_COUNT "toCount"
#define MATCH_STATE_KEY_SUDDEN_RESPAWNS "sdRespawns"
#define MATCH_STATE_KEY_SUDDEN_START "sdStart"
#define MATCH_STATE_KEY_SUDDEN_TICK "sdTick"
#define MATCH_STATE_KEY_SUDDEN_MAX "sdMax"
#define MATCH_STATE_KEY_SUDDEN_INCREMENT "sdInc"
#define MATCH_STATE_KEY_SUDDEN_PRINT "sdPrint"
#define MATCH_STATE_KEY_SUDDEN_DELAY "sdDelay"

#endif // MATCH_STATE_KEYS_H
