#ifndef PLATFORM_CONFIG_H
#define PLATFORM_CONFIG_H

#ifndef QL_BUILD_ONLINE_SERVICES
#define QL_BUILD_ONLINE_SERVICES 0
#endif

#if !QL_BUILD_ONLINE_SERVICES
#undef QL_BUILD_STEAMWORKS
#define QL_BUILD_STEAMWORKS 0
#undef QL_BUILD_OPEN_STEAM
#define QL_BUILD_OPEN_STEAM 0
#else
#ifndef QL_BUILD_STEAMWORKS
#define QL_BUILD_STEAMWORKS 0
#endif

#ifndef QL_BUILD_OPEN_STEAM
#define QL_BUILD_OPEN_STEAM 0
#endif
#endif

#if QL_BUILD_ONLINE_SERVICES
#define QL_PLATFORM_HAS_ONLINE_SERVICES 1
#else
#define QL_PLATFORM_HAS_ONLINE_SERVICES 0
#endif

#ifndef QL_ENABLE_LEGACY_Q3_SERVICES
#define QL_ENABLE_LEGACY_Q3_SERVICES 0
#endif

#if !QL_PLATFORM_HAS_ONLINE_SERVICES
#undef QL_ENABLE_LEGACY_Q3_SERVICES
#define QL_ENABLE_LEGACY_Q3_SERVICES 0
#endif

#if QL_BUILD_STEAMWORKS
#define QL_PLATFORM_HAS_STEAMWORKS 1
#else
#define QL_PLATFORM_HAS_STEAMWORKS 0
#endif

#if QL_BUILD_OPEN_STEAM
#define QL_PLATFORM_HAS_OPEN_STEAM 1
#else
#define QL_PLATFORM_HAS_OPEN_STEAM 0
#endif

#if QL_PLATFORM_HAS_STEAMWORKS && QL_PLATFORM_HAS_OPEN_STEAM
#define QL_PLATFORM_BUILD_HYBRID 1
#else
#define QL_PLATFORM_BUILD_HYBRID 0
#endif

#if QL_PLATFORM_HAS_STEAMWORKS || QL_PLATFORM_HAS_OPEN_STEAM
#define QL_PLATFORM_HAS_STEAM_SERVICES 1
#else
#define QL_PLATFORM_HAS_STEAM_SERVICES 0
#endif

#endif // PLATFORM_CONFIG_H
