#ifndef PLATFORM_CONFIG_H
#define PLATFORM_CONFIG_H

#ifndef QL_BUILD_STEAMWORKS
#define QL_BUILD_STEAMWORKS 0
#endif

#ifndef QL_BUILD_OPEN_STEAM
# if QL_BUILD_STEAMWORKS
#  define QL_BUILD_OPEN_STEAM 0
# else
#  define QL_BUILD_OPEN_STEAM 1
# endif
#endif

#if QL_BUILD_STEAMWORKS
#define QL_PLATFORM_HAS_STEAMWORKS 1
#else
#define QL_PLATFORM_HAS_STEAMWORKS 0
#endif

#if QL_BUILD_OPEN_STEAM
#define QL_PLATFORM_HAS_OPEN_STEAM 1
#else
#define QL_PLATFORM_HAS_OPEN_STEAM 0
#endif

#if QL_PLATFORM_HAS_STEAMWORKS && QL_PLATFORM_HAS_OPEN_STEAM
#define QL_PLATFORM_BUILD_HYBRID 1
#else
#define QL_PLATFORM_BUILD_HYBRID 0
#endif

#endif // PLATFORM_CONFIG_H
