from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent


def _extract_function_block(text: str, signature: str) -> str:
	start = text.find(signature)
	if start == -1:
		raise AssertionError(f"function signature not found: {signature}")

	brace_start = text.find("{", start)
	if brace_start == -1:
		raise AssertionError(f"opening brace not found for: {signature}")

	depth = 0
	for index in range(brace_start, len(text)):
		char = text[index]
		if char == "{":
			depth += 1
		elif char == "}":
			depth -= 1
			if depth == 0:
				return text[start : index + 1]

	raise AssertionError(f"unterminated function block for: {signature}")


def test_common_config_bootstrap_and_writers_match_retail_client_split() -> None:
	common = (REPO_ROOT / "src/code/qcommon/common.c").read_text(encoding="utf-8")

	assert '#define QL_CONFIG_HARDWARE_FILE "qzconfig.cfg"' in common
	assert '#define QL_CONFIG_REPLICATE_FILE "repconfig.cfg"' in common
	assert '#define QL_CONFIG_HARDWARE_HEADER "// Hardware cfg - Generated by QUAKE LIVE. Do not modify\\n"' in common
	assert '#define QL_CONFIG_REPLICATE_HEADER "// Replicate cfg - Generated by QUAKE LIVE. Do not modify\\n"' in common
	assert '#define QL_CDKEY_PLACEHOLDER "                "' in common

	init_block = _extract_function_block(common, "void Com_Init( char *commandLine ) {")
	assert 'Cbuf_AddText ("exec default.cfg\\n");' in init_block
	assert 'Cbuf_AddText ("exec " QL_CONFIG_HARDWARE_FILE "\\n");' in init_block
	assert 'Cbuf_AddText ("exec " QL_CONFIG_REPLICATE_FILE "\\n");' in init_block
	assert 'Cbuf_AddText ("exec autoexec.cfg\\n");' in init_block
	assert 'cvar_modifiedFlags &= ~( CVAR_ARCHIVE | CVAR_CLOUD );' in init_block
	assert 'Cmd_AddCommand ("writeClientConfig", Com_WriteClientConfig_f );' in init_block

	open_block = _extract_function_block(common, "static fileHandle_t Com_OpenRetailConfigFile( const char *filename, const char *header ) {")
	assert 'FS_Printf( f, "%s", header );' in open_block

	write_to_file_block = _extract_function_block(common, "void Com_WriteConfigToFile( const char *hardwareFilename, const char *replicateFilename, qboolean clientConfigOnly ) {")
	assert 'Com_OpenRetailConfigFile( hardwareFilename, QL_CONFIG_HARDWARE_HEADER );' in write_to_file_block
	assert 'Com_OpenRetailConfigFile( replicateFilename, QL_CONFIG_REPLICATE_HEADER );' in write_to_file_block
	assert 'Key_WriteBindings( hardwareFile );' in write_to_file_block
	assert 'Cvar_WriteQLConfigVariables( hardwareFile, replicateFile, clientConfigOnly );' in write_to_file_block

	write_config_block = _extract_function_block(common, "void Com_WriteConfiguration( void ) {")
	assert 'if ( !com_dedicated->integer ) {' in write_config_block
	assert 'Com_WriteConfigToFile( QL_CONFIG_HARDWARE_FILE, QL_CONFIG_REPLICATE_FILE, qfalse );' in write_config_block
	assert 'Com_WriteCDKey( fs->string, cl_cdkey_mod );' in write_config_block
	assert 'Com_WriteCDKey( "baseq3", cl_cdkey );' in write_config_block

	write_config_cmd_block = _extract_function_block(common, "void Com_WriteConfig_f( void ) {")
	assert 'Com_Printf( "Usage: writeconfig <filename> [<rep filename>]\\n" );' in write_config_cmd_block
	assert 'Com_Printf( "Writing hardware cfg %s. Replicated cfg %s\\n", hardwareFilename, replicateFilename );' in write_config_cmd_block
	assert 'Com_WriteConfigToFile( hardwareFilename, replicateFilename, qfalse );' in write_config_cmd_block

	write_client_cmd_block = _extract_function_block(common, "void Com_WriteClientConfig_f( void ) {")
	assert 'Com_Printf( "Usage: writeClientConfig <filename>\\n" );' in write_client_cmd_block
	assert 'Com_WriteConfigToFile( filename, NULL, qtrue );' in write_client_cmd_block


def test_common_cdkey_persistence_is_legacy_placeholder_only() -> None:
	common = (REPO_ROOT / "src/code/qcommon/common.c").read_text(encoding="utf-8")

	placeholder_block = _extract_function_block(common, "static qboolean Com_IsPlaceholderCDKey( const char *key ) {")
	assert "if ( key[i] != ' ' ) {" in placeholder_block

	store_block = _extract_function_block(common, "static void Com_SetStoredCDKeyValue( char *buffer, size_t bufferSize, const char *value ) {")
	assert "buffer[i] = ' ';" in store_block
	assert 'buffer[CDKEY_LEN] = \'\\0\';' in store_block

	load_block = _extract_function_block(common, "static void Com_LoadStoredCDKey( const char *filename, char *buffer, size_t bufferSize ) {")
	assert 'Com_sprintf( path, sizeof( path ), "%s/q3key", filename );' in load_block
	assert 'readLen = FS_Read( key, CDKEY_LEN, f );' in load_block
	assert 'if ( Com_IsPlaceholderCDKey( key ) || CL_CDKeyValidate( key, NULL ) ) {' in load_block

	write_block = _extract_function_block(common, "static void Com_WriteCDKey( const char *filename, const char *ikey ) {")
	assert 'Com_SetStoredCDKeyValue( key, sizeof( key ), ikey );' in write_block
	assert 'if ( !Com_IsPlaceholderCDKey( key ) && !CL_CDKeyValidate( key, NULL ) ) {' in write_block
	assert 'FS_Write( key, CDKEY_LEN, f );' in write_block
	assert 'FS_Printf( f, QL_CDKEY_FILE_NOTE_0 );' in write_block
	assert 'FS_Printf( f, QL_CDKEY_FILE_NOTE_1 );' in write_block
	assert 'FS_Printf( f, QL_CDKEY_FILE_NOTE_2 );' in write_block


def test_ui_and_client_cdkey_surface_revert_to_retail_legacy_behavior() -> None:
	cl_ui = (REPO_ROOT / "src/code/client/cl_ui.c").read_text(encoding="utf-8")
	cl_main = (REPO_ROOT / "src/code/client/cl_main.c").read_text(encoding="utf-8")

	sync_block = _extract_function_block(cl_ui, "static void CLUI_SyncCredentialCvars( const char *rawValue ) {")
	assert '(void)rawValue;' in sync_block
	assert 'Cvar_SetValue( "ui_credentialKind", (float)QL_AUTH_CREDENTIAL_LEGACY_CDKEY );' in sync_block
	assert 'Cvar_Set( "ui_credentialAuto", "0" );' in sync_block
	assert 'Cvar_Set( "ui_credentialManualHidden", "0" );' in sync_block

	copy_block = _extract_function_block(cl_ui, "static void CLUI_CopyCDKeyValue( char *dest, size_t destSize, const char *src ) {")
	assert "dest[i] = ' ';" in copy_block
	assert 'dest[CDKEY_LEN] = \'\\0\';' in copy_block

	get_block = _extract_function_block(cl_ui, "static void CLUI_GetCDKey( char *buf, int buflen ) {")
	assert 'CLUI_CopyCDKeyValue( buf, (size_t)buflen, source );' in get_block

	set_block = _extract_function_block(cl_ui, "static void CLUI_SetCDKey( char *buf ) {")
	assert 'CLUI_CopyCDKeyValue( cl_cdkey_mod, sizeof( cl_cdkey_mod ), input );' in set_block
	assert 'CLUI_CopyCDKeyValue( cl_cdkey, sizeof( cl_cdkey ), input );' in set_block
	assert 'cvar_modifiedFlags |= CVAR_ARCHIVE;' in set_block

	validate_block = _extract_function_block(cl_main, "qboolean CL_CDKeyValidate( const char *key, const char *checksum ) {")
	assert 'return CL_CDKeyValidateLegacyValue( key, checksum );' in validate_block


def test_restart_bootstrap_queues_qzconfig_after_game_directory_changes() -> None:
	files = (REPO_ROOT / "src/code/qcommon/files.c").read_text(encoding="utf-8")
	restart_block = _extract_function_block(files, "void FS_Restart( int checksumFeed ) {")

	assert 'Cbuf_AddText ("exec qzconfig.cfg\\n");' in restart_block


def test_cvar_writer_routes_retail_replicate_and_client_config_sets() -> None:
	cvar = (REPO_ROOT / "src/code/qcommon/cvar.c").read_text(encoding="utf-8")
	block = _extract_function_block(cvar, "void Cvar_WriteQLConfigVariables( fileHandle_t hardwareFile, fileHandle_t replicateFile, qboolean clientConfigOnly ) {")

	assert 'if ( !Q_stricmp( var->name, "cl_cdkey" ) || !Q_stricmp( var->name, "password" ) ) {' in block
	assert 'if ( !( var->flags & ( CVAR_ARCHIVE | CVAR_PROTECTED ) ) ) {' in block
	assert 'if ( clientConfigOnly ) {' in block
	assert 'if ( !( var->flags & CVAR_CLOUD ) ) {' in block
	assert 'if ( !Q_stricmp( value, var->resetString ? var->resetString : "" ) ) {' in block
	assert 'if ( ( var->flags & CVAR_PROTECTED ) || ( (unsigned int)var->flags & 0x80000000u ) ) {' in block
	assert 'Com_sprintf( buffer, sizeof( buffer ), "seta %s \\"%s\\"\\n", var->name, value );' in block
