/*
===========================================================================
Copyright (C) 1999-2005 Id Software, Inc.

This file is part of Quake III Arena source code.

Quake III Arena source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

Quake III Arena source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Foobar; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
===========================================================================
*/
//


#define	CMD_BACKUP			64	
#define	CMD_MASK			(CMD_BACKUP - 1)
// allow a lot of command backups for very fast systems
// multiple commands may be combined into a single packet, so this
// needs to be larger than PACKET_BACKUP


#define	MAX_ENTITIES_IN_SNAPSHOT	256

// snapshots are a view of the server at a given time

// Snapshots are generated at regular time intervals by the server,
// but they may not be sent if a client's rate level is exceeded, or
// they may be dropped by the network.
typedef struct {
	int				snapFlags;			// SNAPFLAG_RATE_DELAYED, etc
	int				ping;

	int				serverTime;		// server time the message is valid for (in msec)

	byte			areamask[MAX_MAP_AREA_BYTES];		// portalarea visibility bits

	playerState_t	ps;						// complete information about the current player at this time

	int				numEntities;			// all of the entities that need to be presented
	entityState_t	entities[MAX_ENTITIES_IN_SNAPSHOT];	// at the time of this snapshot

	int				numServerCommands;		// text based server commands to execute when this
	int				serverCommandSequence;	// snapshot becomes current
} snapshot_t;

typedef enum {
	CGAME_EVENT_NONE,
	CGAME_EVENT_TEAMMENU,
	CGAME_EVENT_SCOREBOARD,
	CGAME_EVENT_EDITHUD,
	CGAME_EVENT_REFRESH_DISPLAY_CONTEXT,
	CGAME_EVENT_CLOSECOMMANDOVERLAY
} cgameEvent_t;

#define CG_CLIENT_IDENTITY_NAME_CHARS	40

typedef struct {
	int				clientNum;
	unsigned int	identityTransport;
	unsigned int	identityLow;
	unsigned int	identityHigh;
	char			displayName[CG_CLIENT_IDENTITY_NAME_CHARS];
	char			cleanName[CG_CLIENT_IDENTITY_NAME_CHARS];
} cgameClientIdentity_t;


/*
==================================================================

functions imported from the main executable

==================================================================
*/

#define	CGAME_IMPORT_API_VERSION	4
#define	CGAME_NATIVE_API_VERSION	8

// Legacy cgame syscall order shared by QVMs and classic DLLs.
typedef enum {
	CG_PRINT,
	CG_ERROR,
	CG_MILLISECONDS,
	CG_CVAR_REGISTER,
	CG_CVAR_UPDATE,
	CG_CVAR_SET,
	CG_CVAR_VARIABLESTRINGBUFFER,
	CG_ARGC,
	CG_ARGV,
	CG_ARGS,
	CG_FS_FOPENFILE,
	CG_FS_READ,
	CG_FS_WRITE,
	CG_FS_FCLOSEFILE,
	CG_SENDCONSOLECOMMAND,
	CG_ADDCOMMAND,
	CG_SENDCLIENTCOMMAND,
	CG_UPDATESCREEN,
	CG_CM_LOADMAP,
	CG_CM_NUMINLINEMODELS,
	CG_CM_INLINEMODEL,
	CG_CM_LOADMODEL,
	CG_CM_TEMPBOXMODEL,
	CG_CM_POINTCONTENTS,
	CG_CM_TRANSFORMEDPOINTCONTENTS,
	CG_CM_BOXTRACE,
	CG_CM_TRANSFORMEDBOXTRACE,
	CG_CM_MARKFRAGMENTS,
	CG_S_STARTSOUND,
	CG_S_STARTLOCALSOUND,
	CG_S_CLEARLOOPINGSOUNDS,
	CG_S_ADDLOOPINGSOUND,
	CG_S_UPDATEENTITYPOSITION,
	CG_S_RESPATIALIZE,
	CG_S_REGISTERSOUND,
	CG_S_STARTBACKGROUNDTRACK,
	CG_R_LOADWORLDMAP,
	CG_R_REGISTERMODEL,
	CG_R_REGISTERSKIN,
	CG_R_REGISTERSHADER,
	CG_R_CLEARSCENE,
	CG_R_ADDREFENTITYTOSCENE,
	CG_R_ADDPOLYTOSCENE,
	CG_R_ADDLIGHTTOSCENE,
	CG_R_RENDERSCENE,
	CG_R_SETCOLOR,
	CG_R_DRAWSTRETCHPIC,
	CG_R_MODELBOUNDS,
	CG_R_LERPTAG,
	CG_GETGLCONFIG,
	CG_GETGAMESTATE,
	CG_GETCURRENTSNAPSHOTNUMBER,
	CG_GETSNAPSHOT,
	CG_GETSERVERCOMMAND,
	CG_GETCURRENTCMDNUMBER,
	CG_GETUSERCMD,
	CG_SETUSERCMDVALUE,
	CG_R_REGISTERSHADERNOMIP,
	CG_MEMORY_REMAINING,
	CG_R_REGISTERFONT,
	CG_KEY_ISDOWN,
	CG_KEY_GETCATCHER,
	CG_KEY_SETCATCHER,
	CG_KEY_GETKEY,
 	CG_PC_ADD_GLOBAL_DEFINE,
	CG_PC_LOAD_SOURCE,
	CG_PC_FREE_SOURCE,
	CG_PC_READ_TOKEN,
	CG_PC_SOURCE_FILE_AND_LINE,
	CG_S_STOPBACKGROUNDTRACK,
	CG_REAL_TIME,
	CG_SNAPVECTOR,
	CG_REMOVECOMMAND,
	CG_R_LIGHTFORPOINT,
	CG_CIN_PLAYCINEMATIC,
	CG_CIN_STOPCINEMATIC,
	CG_CIN_RUNCINEMATIC,
	CG_CIN_DRAWCINEMATIC,
	CG_CIN_SETEXTENTS,
	CG_R_REMAP_SHADER,
	CG_S_ADDREALLOOPINGSOUND,
	CG_S_STOPLOOPINGSOUND,

	CG_CM_TEMPCAPSULEMODEL,
	CG_CM_CAPSULETRACE,
	CG_CM_TRANSFORMEDCAPSULETRACE,
	CG_R_ADDADDITIVELIGHTTOSCENE,
	CG_GET_ENTITY_TOKEN,
	CG_R_ADDPOLYSTOSCENE,
	CG_R_INPVS,
	// 1.32
	CG_FS_SEEK,
	CG_KEY_KEYNUMTOSTRINGBUF,
	CG_KEY_GETBINDINGBUF,
	CG_KEY_SETBINDING,
	CG_KEY_GETOVERSTRIKEMODE,
	CG_KEY_SETOVERSTRIKEMODE,
	CG_CMD_EXECUTETEXT,

/*
	CG_LOADCAMERA,
	CG_STARTCAMERA,
	CG_GETCAMERAINFO,
*/

	CG_MEMSET = 100,
	CG_MEMCPY,
	CG_STRNCPY,
	CG_SIN,
	CG_COS,
	CG_ATAN2,
	CG_SQRT,
	CG_FLOOR,
	CG_CEIL,
	CG_TESTPRINTINT,
	CG_TESTPRINTFLOAT,
	CG_ACOS,
	CG_ADVERTISEMENTBRIDGE_INITCGAME,
	CG_ADVERTISEMENTBRIDGE_SHUTDOWNCGAME,
	CG_ADVERTISEMENTBRIDGE_UPDATELOADINGVIEWPARAMETERS,
	CG_ADVERTISEMENTBRIDGE_SETFRAMETIME
} cgameImport_t;

// Retail Quake Live native DLL import slab recovered from cgamex86.dll. Unnamed gaps stay deliberately
// unbound until the committed HLIL/Ghidra corpus closes them more cleanly.
typedef enum {
	CG_QL_IMPORT_PRINT = 0,
	CG_QL_IMPORT_ERROR = 1,
	CG_QL_IMPORT_MILLISECONDS = 2,
	CG_QL_IMPORT_REAL_TIME = 3,
	CG_QL_IMPORT_CVAR_REGISTER = 4,
	CG_QL_IMPORT_CVAR_REGISTER_RANGE = 5,
	CG_QL_IMPORT_CVAR_UPDATE = 6,
	CG_QL_IMPORT_CVAR_SET = 7,
	CG_QL_IMPORT_CVAR_VARIABLESTRINGBUFFER = 9,
	CG_QL_IMPORT_CVAR_RESET = 10,
	CG_QL_IMPORT_ARGC = 11,
	CG_QL_IMPORT_ARGV = 12,
	CG_QL_IMPORT_ARGS = 13,
	CG_QL_IMPORT_FS_FOPENFILE = 14,
	CG_QL_IMPORT_FS_READ = 15,
	CG_QL_IMPORT_FS_WRITE = 16,
	CG_QL_IMPORT_FS_FCLOSEFILE = 17,
	CG_QL_IMPORT_FS_SEEK = 18,
	CG_QL_IMPORT_FS_GETFILELIST = 19,
	CG_QL_IMPORT_SENDCONSOLECOMMAND = 20,
	CG_QL_IMPORT_ADDCOMMAND = 21,
	CG_QL_IMPORT_REMOVECOMMAND = 22,
	CG_QL_IMPORT_SENDCLIENTCOMMAND = 23,
	CG_QL_IMPORT_UPDATESCREEN = 24,
	CG_QL_IMPORT_CM_LOADMAP = 25,
	CG_QL_IMPORT_CM_NUMINLINEMODELS = 26,
	CG_QL_IMPORT_CM_INLINEMODEL = 27,
	CG_QL_IMPORT_CM_TEMPBOXMODEL = 28,
	CG_QL_IMPORT_CM_TEMPCAPSULEMODEL = 29,
	CG_QL_IMPORT_CM_POINTCONTENTS = 30,
	CG_QL_IMPORT_CM_TRANSFORMEDPOINTCONTENTS = 31,
	CG_QL_IMPORT_CM_BOXTRACE = 32,
	CG_QL_IMPORT_CM_CAPSULETRACE = 33,
	CG_QL_IMPORT_CM_TRANSFORMEDBOXTRACE = 34,
	CG_QL_IMPORT_CM_TRANSFORMEDCAPSULETRACE = 35,
	CG_QL_IMPORT_CM_MARKFRAGMENTS = 36,
	CG_QL_IMPORT_S_STARTSOUND = 37,
	CG_QL_IMPORT_S_STARTSOUND_VOLUME = 38,
	CG_QL_IMPORT_S_STARTLOCALSOUND = 39,
	CG_QL_IMPORT_S_STARTLOCALSOUND_VOLUME = 40,
	CG_QL_IMPORT_S_CLEARLOOPINGSOUNDS_FRAME = 41,
	CG_QL_IMPORT_S_CLEARLOOPINGSOUNDS_KILLALL = 42,
	CG_QL_IMPORT_S_ADDLOOPINGSOUND = 43,
	CG_QL_IMPORT_S_UPDATEENTITYPOSITION = 44,
	CG_QL_IMPORT_S_RESPATIALIZE = 45,
	CG_QL_IMPORT_S_REGISTERSOUND = 46,
	CG_QL_IMPORT_S_STARTBACKGROUNDTRACK = 47,
	CG_QL_IMPORT_S_STOPBACKGROUNDTRACK = 48,
	CG_QL_IMPORT_R_LOADWORLDMAP = 49,
	CG_QL_IMPORT_R_REGISTERMODEL = 50,
	CG_QL_IMPORT_R_REGISTERSKIN = 51,
	CG_QL_IMPORT_R_REGISTERSHADER = 52,
	CG_QL_IMPORT_R_REGISTERSHADERNOMIP = 53,
	CG_QL_IMPORT_SETUP_ADVERT_CELL_SHADER = 55,
	CG_QL_IMPORT_REFRESH_ADVERT_CELL_SHADER = 56,
	CG_QL_IMPORT_SET_ACTIVE_ADVERT = 57,
	CG_QL_IMPORT_UPDATE_ADVERT = 58,
	CG_QL_IMPORT_ADVERTISEMENTBRIDGE_SET_MAP_PATH = 60,
	CG_QL_IMPORT_ADVERTISEMENTBRIDGE_INITCGAME = 61,
	CG_QL_IMPORT_ADVERTISEMENTBRIDGE_SHUTDOWNCGAME = 62,
	CG_QL_IMPORT_ADVERTISEMENTBRIDGE_SETFRAMETIME = 64,
	CG_QL_IMPORT_R_CLEARSCENE = 70,
	CG_QL_IMPORT_R_ADDREFENTITYTOSCENE = 71,
	CG_QL_IMPORT_R_ADDPOLYTOSCENE = 72,
	CG_QL_IMPORT_R_ADDPOLYSTOSCENE = 73,
	CG_QL_IMPORT_R_ADDLIGHTTOSCENE = 74,
	CG_QL_IMPORT_R_LIGHTFORPOINT = 75,
	CG_QL_IMPORT_R_RENDERSCENE = 76,
	CG_QL_IMPORT_ADVERTISEMENTBRIDGE_UPDATE_LOADING_VIEW_PARAMETERS = 77,
	CG_QL_IMPORT_R_SETCOLOR = 78,
	CG_QL_IMPORT_R_DRAWSTRETCHPIC = 79,
	CG_QL_IMPORT_R_MODELBOUNDS = 81,
	CG_QL_IMPORT_R_LERPTAG = 82,
	CG_QL_IMPORT_R_REMAP_SHADER = 83,
	CG_QL_IMPORT_GETGLCONFIG = 84,
	CG_QL_IMPORT_GETGAMESTATE = 85,
	CG_QL_IMPORT_GETCURRENTSNAPSHOTNUMBER = 86,
	CG_QL_IMPORT_GETSNAPSHOT = 87,
	CG_QL_IMPORT_GETSERVERCOMMAND = 88,
	CG_QL_IMPORT_GETCURRENTCMDNUMBER = 89,
	CG_QL_IMPORT_GETUSERCMD = 90,
	CG_QL_IMPORT_SETUSERCMDVALUE = 91,
	CG_QL_IMPORT_MEMORY_REMAINING = 92,
	CG_QL_IMPORT_R_REGISTERFONT = 93,
	CG_QL_IMPORT_KEY_ISDOWN = 94,
	CG_QL_IMPORT_KEY_GETCATCHER = 95,
	CG_QL_IMPORT_KEY_SETCATCHER = 96,
	CG_QL_IMPORT_KEY_GETKEY = 97,
	CG_QL_IMPORT_KEY_KEYNUMTOSTRINGBUF = 98,
	CG_QL_IMPORT_KEY_GETBINDINGBUF = 99,
	CG_QL_IMPORT_CIN_PLAYCINEMATIC = 101,
	CG_QL_IMPORT_CIN_STOPCINEMATIC = 102,
	CG_QL_IMPORT_CIN_RUNCINEMATIC = 103,
	CG_QL_IMPORT_CIN_DRAWCINEMATIC = 104,
	CG_QL_IMPORT_CIN_SETEXTENTS = 105,
	CG_QL_IMPORT_GET_ENTITY_TOKEN = 106,
	CG_QL_IMPORT_PC_LOAD_SOURCE = 108,
	CG_QL_IMPORT_PC_FREE_SOURCE = 109,
	CG_QL_IMPORT_PC_READ_TOKEN = 110,
	CG_QL_IMPORT_PC_SOURCE_FILE_AND_LINE = 111,
	CG_QL_IMPORT_ADVERTISEMENTBRIDGE_UPDATE_VIEW_PARAMETERS = 114,
	CG_QL_IMPORT_ADVERTISEMENTBRIDGE_CLEAR_DELAY = 115,
	CG_QL_IMPORT_TAGGED_CVAR_STRING_BUFFER = 116,
	CG_QL_IMPORT_R_MIRROR_POINT = 120,
	CG_QL_IMPORT_R_MIRROR_VECTOR = 121,
	CG_QL_IMPORT_DRAW_SCALED_TEXT = 123,
	CG_QL_IMPORT_MEASURE_TEXT = 124,
	CG_QL_IMPORT_IS_CLIENT_MUTED = 125,
	CG_QL_IMPORT_TOGGLE_CLIENT_MUTE = 126,
	CG_QL_IMPORT_GET_AVATAR_IMAGE_HANDLE = 127,

	CG_QL_IMPORT_COUNT = 128,

	// Source-side compatibility slots beyond the recovered retail slab.
	CG_QL_IMPORT_COMPAT_CM_LOADMODEL = CG_QL_IMPORT_COUNT,
	CG_QL_IMPORT_COMPAT_S_ADDREALLOOPINGSOUND,
	CG_QL_IMPORT_COMPAT_S_STOPLOOPINGSOUND,
	CG_QL_IMPORT_COMPAT_R_ADDADDITIVELIGHTTOSCENE,
	CG_QL_IMPORT_COMPAT_R_INPVS,
	CG_QL_IMPORT_COMPAT_KEY_SETBINDING,
	CG_QL_IMPORT_COMPAT_KEY_GETOVERSTRIKEMODE,
	CG_QL_IMPORT_COMPAT_KEY_SETOVERSTRIKEMODE,
	CG_QL_IMPORT_COMPAT_CMD_EXECUTETEXT,
	CG_QL_IMPORT_COMPAT_PC_ADD_GLOBAL_DEFINE,
	CG_QL_IMPORT_COMPAT_REAL_TIME,
	CG_QL_IMPORT_COMPAT_SNAPVECTOR,
	CG_QL_IMPORT_COMPAT_MEMSET,
	CG_QL_IMPORT_COMPAT_MEMCPY,
	CG_QL_IMPORT_COMPAT_STRNCPY,
	CG_QL_IMPORT_COMPAT_SIN,
	CG_QL_IMPORT_COMPAT_COS,
	CG_QL_IMPORT_COMPAT_ATAN2,
	CG_QL_IMPORT_COMPAT_SQRT,
	CG_QL_IMPORT_COMPAT_FLOOR,
	CG_QL_IMPORT_COMPAT_CEIL,
	CG_QL_IMPORT_COMPAT_TESTPRINTINT,
	CG_QL_IMPORT_COMPAT_TESTPRINTFLOAT,
	CG_QL_IMPORT_COMPAT_ACOS,
	CG_QL_IMPORT_TOTAL_COUNT
} cgameNativeImport_t;

#define CGAME_NATIVE_IMPORT_COUNT	CG_QL_IMPORT_TOTAL_COUNT


/*
==================================================================

functions exported to the main executable

==================================================================
*/

// Legacy vmMain call order shared by QVMs and classic DLLs.
typedef enum {
	CG_INIT,
//	void CG_Init( int serverMessageNum, int serverCommandSequence, int clientNum )
	// called when the level loads or when the renderer is restarted
	// all media should be registered at this time
	// cgame will display loading status by calling SCR_Update, which
	// will call CG_DrawInformation during the loading process
	// reliableCommandSequence will be 0 on fresh loads, but higher for
	// demos, tourney restarts, or vid_restarts

	CG_SHUTDOWN,
//	void (*CG_Shutdown)( void );
	// oportunity to flush and close any open files

	CG_CONSOLE_COMMAND,
//	qboolean (*CG_ConsoleCommand)( void );
	// a console command has been issued locally that is not recognized by the
	// main game system.
	// use Cmd_Argc() / Cmd_Argv() to read the command, return qfalse if the
	// command is not known to the game

	CG_DRAW_ACTIVE_FRAME,
//	void (*CG_DrawActiveFrame)( int serverTime, stereoFrame_t stereoView, qboolean demoPlayback );
	// Generates and draws a game scene and status information at the given time.
	// If demoPlayback is set, local movement prediction will not be enabled

	CG_CROSSHAIR_PLAYER,
//	int (*CG_CrosshairPlayer)( void );

	CG_LAST_ATTACKER,
//	int (*CG_LastAttacker)( void );

	CG_KEY_EVENT, 
//	void	(*CG_KeyEvent)( int key, qboolean down );

	CG_MOUSE_EVENT,
//	void	(*CG_MouseEvent)( int dx, int dy );
	CG_EVENT_HANDLING,
//	void (*CG_EventHandling)(int type);
	CG_CHAT_DOWN,
	CG_CHAT_UP,
	CG_SHOW_1ST_TRACKED_PLAYER,
	CG_SHOW_2ND_TRACKED_PLAYER,
	CG_COPY_CLIENT_IDENTITY,
	CG_GET_CHAT_FIELD_Y,
	CG_GET_CHAT_FIELD_PIXEL_WIDTH,
	CG_GET_CHAT_FIELD_WIDTH_IN_CHARS,
	CG_SET_CLIENT_SPEAKING_STATE,
	CG_GET_PHYSICS_TIME
} cgameExport_t;

// Retail Quake Live native DLL slot order recovered from cgamex86.dll dllEntry().
typedef enum {
	CG_NATIVE_EXPORT_INIT,
	CG_NATIVE_EXPORT_REGISTER_CVARS,
	CG_NATIVE_EXPORT_SHUTDOWN,
	CG_NATIVE_EXPORT_CONSOLE_COMMAND,
	CG_NATIVE_EXPORT_DRAW_ACTIVE_FRAME,
	CG_NATIVE_EXPORT_CROSSHAIR_PLAYER,
	CG_NATIVE_EXPORT_LAST_ATTACKER,
	CG_NATIVE_EXPORT_KEY_EVENT,
	CG_NATIVE_EXPORT_MOUSE_EVENT,
	CG_NATIVE_EXPORT_EVENT_HANDLING,
	CG_NATIVE_EXPORT_SHOW_1ST_TRACKED_PLAYER,
	CG_NATIVE_EXPORT_SHOW_2ND_TRACKED_PLAYER,
	CG_NATIVE_EXPORT_CHAT_DOWN,
	CG_NATIVE_EXPORT_CHAT_UP,
	CG_NATIVE_EXPORT_GET_PHYSICS_TIME,
	CG_NATIVE_EXPORT_COPY_CLIENT_IDENTITY,
	CG_NATIVE_EXPORT_RESERVED_NULL,		// observed null slot at data_100769e8 in retail cgamex86.dll
	CG_NATIVE_EXPORT_GET_CHAT_FIELD_Y,
	CG_NATIVE_EXPORT_GET_CHAT_FIELD_PIXEL_WIDTH,
	CG_NATIVE_EXPORT_GET_CHAT_FIELD_WIDTH_IN_CHARS,
	CG_NATIVE_EXPORT_SET_CLIENT_SPEAKING_STATE,
	CG_NATIVE_EXPORT_COUNT
} cgameNativeExport_t;

//----------------------------------------------
