//**********************************************************************//
//	gfx.shader updated						//
//	by Eutectic - 23 Jan 2000					//
//	This file is irrelevant for Q3Radiant				//
//	It was updated for sake of completeness:			//
//	shaders that belong here were moved from other shader files	//
//									//
//	SHADERS THAT DIDN'T BELONG HERE AND MOVED TO PROPER FILE: 0	//
//	SHADERS THAT BELONGED HERE BUT WERE IN ANOTHER FILE: 6		//
//	powerups/blueflag						//
//	powerups/redflag						//
//	sprites/friend							//
//	sprites/plasma1							//
//	sprites/plasma2							//
//**********************************************************************//

// GFX.SHADER
// 
// this file contains shaders that are used by the programmers to
// generate special effects not attached to specific geometry.  This
// also has 2D shaders such as fonts, etc.
//

// the REGION shader is generated by the map editor on temporary
// brushes around a selected area for testing parts of maps

textures/REGION
{
	surfaceparm nolightmap
}

// the background for the netgraph
lagometer
{
	nopicmip
	{
		map gfx/2d/lag.tga
	}
}

// blinked on top of lagometer when connection is interrupted
disconnected
{
	nopicmip
	{
		map gfx/2d/net.tga
	}
}

white
{
	{
		map *white
		blendfunc	GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

console
{
	nopicmip
	nomipmaps
    
        {
		map gfx/misc/console01.tga
                blendfunc GL_ONE GL_ZERO
                tcMod scroll .02  0
                tcmod scale 2 1
	}
        {
                map gfx/misc/console02.tga
                //map textures/sfx/firegorre3.tga
                blendfunc add
                tcMod turb 0 .1 0 .1
                tcMod scale 2 1
                tcmod scroll 0.2  .1
	} 

}

browserShader
{
	nopicmip
	{
		map *white
		blendfunc blend
	}
}

menuback
{
	nopicmip
	nomipmaps
        //{
        //        map textures/sfx/logo512.tga
        //}

        //{
        //        map textures/sfx/specular.tga
         //       //blendfunc add
        //        tcMod turb 0 .8 0 .2
        //        tcmod scroll -.1  -.2
	//} 
         {
                map textures/sfx/logo512.tga
                // blendfunc blend
                rgbgen identity
        }
        //{
	//	map textures/sfx/proto_zzzdrk.tga
        //        blendfunc add
        //        tcMod turb 0 .1 0 .9
        //         tcmod scale .2 .2
        //         tcMod scroll .02  0.7
        //         rgbgen identity
	//} 
        
}
menubacknologo
{
	nopicmip
	nomipmaps
       
        {
               map gfx/colors/black.tga
	       //map textures/sfx/proto_zzzdrk.tga
               // tcMod turb 0 .1 0 .9
               // tcmod scale .2 .2
               // tcMod scroll .02  0.7
	} 
        
}

menubackRagePro	// blends turn to shit on rage pro, so skip it
{
	nopicmip
	nomipmaps
        {
                map textures/sfx/logo512.tga
        }
        
}


levelShotDetail
// used to break up the blur on levelshots
{
	nopicmip
	{
		map textures/sfx/detail.tga
        blendfunc GL_DST_COLOR GL_SRC_COLOR
		rgbgen identity
	}
}

//
// special effects as seen on players
//

powerups/battleSuit
{
	nopicmip
	deformVertexes wave 100 sin 1 0 0 0
	{
		map textures/effects/envmapgold2.tga
                //map textures/sfx/specular.tga
		tcGen environment
		tcMod turb 0 0.15 0 0.3
                tcmod rotate 333
                tcmod scroll .3 .3
		blendfunc add
	}
}

powerups/battleWeapon
{
	nopicmip
	deformVertexes wave 100 sin 0.5 0 0 0
	{
		map textures/effects/envmapgold2.tga
                //map textures/sfx/specular.tga
		tcGen environment
		tcMod turb 0 0.15 0 0.3
                tcmod rotate 333
                tcmod scroll .3 .3
		blendfunc add
	}
}

powerups/invisibility
{
	nopicmip
	{
		map textures/effects/invismap.tga
        blendfunc add
		tcMod turb 0 0.15 0 0.25
		tcGen environment
		//blendfunc add
		//rgbGen const ( 0.501961 0.501961 0.501961 )
		//tcMod rotate 30
		//tcMod scroll 1 0.1
		//tcGen environment 
	}
}

ghostWeaponShader
{
	nopicmip
	{
		map textures/effects/translucent.tga
		blendfunc add
		tcGen environment
	}
}

noPlayerClipShader
{
	nopicmip
	{
		map textures/effects/noplayerclip.tga
		blendfunc add
		tcMod turb 0 0.15 0 0.25
		tcGen environment
	}
}

powerups/goo
{
	nopicmip
	deformVertexes wave 100 sin 0.5 0 0 0
	{
		map textures/effects/goo.png
		blendfunc blend
		//tcGen environment
                //tcmod rotate 30
                tcmod scroll 0 -0.05
	}
}

powerups/quad
{
	nopicmip
	deformVertexes wave 100 sin 3 0 0 0
	{
		map textures/effects/quadmap2.tga
		blendfunc add
		tcGen environment
                tcmod rotate 30
		//tcMod turb 0 0.2 0 .2
                tcmod scroll 1 .1
	}
}

powerups/quadWeapon
{
	deformVertexes wave 100 sin 0.5 0 0 0
	{
		map textures/effects/quadmap2.tga
		blendfunc add
		tcGen environment
                tcmod rotate 30
		//tcMod turb 0 0.2 0 .2
                tcmod scroll 1 .1
	}
}

powerups/ice1
{
	nopicmip
	deformVertexes wave 100 sin 1 0 0 0
	{
		map textures/effects/icemap.tga
		blendfunc add
		tcGen environment
        tcmod rotate 30
        tcmod scroll 0.75 -0.075
	}
}

powerups/ice2
{
	nopicmip
	deformVertexes wave 100 sin 2 0 0 0
	{
		map textures/effects/icemap.tga
		blendfunc add
		tcGen environment
        tcmod rotate 30
        tcmod scroll 0.5 -0.05
	}
}

powerups/ice3
{
	nopicmip
	deformVertexes wave 100 sin 3 0 0 0
	{
		map textures/effects/icemap.tga
		blendfunc add
		tcGen environment
        tcmod rotate 30
        tcmod scroll 0.25 -0.025
	}
}

powerups/spawnarmor
{
	nopicmip
	deformVertexes wave 100 sin 3 0 0 0
	{
		map textures/effects/spawnarmormap.tga
		blendfunc add
		tcGen environment
                tcmod rotate 30
		//tcMod turb 0 0.2 0 .2
                tcmod scroll 1 .1
	}
}

powerups/spawnarmor2
{
	nopicmip
	deformVertexes wave 100 sin 3 0 0 0
	{
		map textures/effects/spawnarmormap2.tga
		blendfunc add
		tcGen environment
                tcmod rotate 30
		//tcMod turb 0 0.2 0 .2
                tcmod scroll 1 .1
	}
}

powerups/regen
{
	nopicmip
	deformVertexes wave 100 sin 3 0 0 0
	{
		map textures/effects/regenmap2.tga
		blendfunc add
		tcGen environment
                tcmod rotate 30
		//tcMod turb 0 0.2 0 .2
                tcmod scroll 1 .1
	}
}

powerups/blueflag
{
	nopicmip
	deformVertexes wave 100 sin 3 0 0 0
	{
		map textures/effects/blueflagmap.tga
		blendfunc add
		tcGen environment
		tcMod turb 0 0.2 0 1
	}
}

powerups/redflag
{
	nopicmip
	deformVertexes wave 100 sin 3 0 0 0
	{
		map textures/effects/redflagmap.tga
		blendfunc add
		tcGen environment
		tcMod turb 0 0.2 0 1
	}
}

icons/infinite
{
	nopicmip
	{
		map icons/infinite.tga
		blendfunc blend
		rgbGen vertex
	}
}

icons/skull_red
{
	nopicmip
	{
		map icons/skull_red.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/thaw
{
	nopicmip
	{
		map icons/thaw.tga
		blendfunc blend
		alphaGen vertex
	}
}

//=========================

//
// holdable item icons
//

icons/medkit
{
	nopicmip
	{
		map icons/medkit.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/teleporter
{
	nopicmip
	{
		map icons/teleporter.tga
		blendfunc blend
		alphaGen vertex
	}
}

//
// powerup icons
//
icons/spawnarmor
{
	nopicmip
	{
		map icons/spawnarmor.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/envirosuit
{
	nopicmip
	{
		map icons/envirosuit.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/flight
{
	nopicmip
	{
		map icons/flight.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/haste
{
	nopicmip
	{
		map icons/haste.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/invis
{
	nopicmip
	{
		map icons/invis.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/quad
{
	nopicmip
	{
		map icons/quad.tga
		//blendfunc blend
		//alphaGen vertex
		blendfunc	GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

icons/regen
{
	nopicmip
	{
		map icons/regen.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/kamikaze
{
	nopicmip
	{
		map icons/kamikaze.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/scout
{
	nopicmip
	{
		map icons/scout.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/guard
{
	nopicmip
	{
		map icons/guard.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/doubler
{
	nopicmip
	{
		map icons/doubler.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/invulnerability
{
	nopicmip
	{
		map icons/invulnerability.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/ammo_regen
{
	nopicmip
	{
		map icons/ammo_regen.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/armor_regen
{
	nopicmip
	{
		map icons/armor_regen.tga
		blendfunc blend
		alphaGen vertex
	}
}

// reward medals used in the game floating over client's heads

medal_accuracy
{
	nopicmip
	{
		clampmap menu/medals/medal_accuracy.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_assist
{
	nopicmip
	{
		clampmap menu/medals/medal_assist.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_capture
{
	nopicmip
	{
		clampmap menu/medals/medal_capture.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_combokill
{
	nopicmip
	{
		clampmap menu/medals/medal_combokill.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_damage
{
	nopicmip
	{
		clampmap menu/medals/medal_damage.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_defense
{
	nopicmip
	{
		clampmap menu/medals/medal_defense.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_excellent
{
	nopicmip
	{
		clampmap menu/medals/medal_excellent.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_firstfrag
{
	nopicmip
	{
		clampmap menu/medals/medal_firstfrag.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_gauntlet
{
	nopicmip
	{
		clampmap menu/medals/medal_gauntlet.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_headshot
{
	nopicmip
	{
		clampmap menu/medals/medal_headshot.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_impressive
{
	nopicmip
	{
		clampmap menu/medals/medal_impressive.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_midair
{
	nopicmip
	{
		clampmap menu/medals/medal_midair.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_perfect
{
	nopicmip
	{
		clampmap menu/medals/medal_perfect.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_perforated
{
	nopicmip
	{
		clampmap menu/medals/medal_perforated.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_quadgod
{
	nopicmip
	{
		clampmap menu/medals/medal_quadgod.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_rampage
{
	nopicmip
	{
		clampmap menu/medals/medal_rampage.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_revenge
{
	nopicmip
	{
		clampmap menu/medals/medal_revenge.tga
		blendfunc blend
		alphaGen vertex
	}
}

medal_timing
{
	nopicmip
	{
		clampmap menu/medals/medal_timing.tga
		blendfunc blend
		alphaGen vertex
	}
}

//
// weapon icons
//

icons/iconw_gauntlet
{
	nopicmip
	{
		map icons/iconw_gauntlet.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_machinegun
{
	nopicmip
	{
		map icons/iconw_machinegun.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_rocket
{
	nopicmip
	{
		map icons/iconw_rocket.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_shotgun
{
	nopicmip
	{
		map icons/iconw_shotgun.tga
		blendfunc blend
		rgbgen identitylighting
		alphaGen vertex
	}
}

icons/iconw_grenade
{
	nopicmip
	{
		map icons/iconw_grenade.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_lightning
{
	nopicmip
	{
		map icons/iconw_lightning.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_plasma
{
	nopicmip
	{
		map icons/iconw_plasma.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_railgun
{
	nopicmip
	{
		map icons/iconw_railgun.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_bfg
{
	nopicmip
	{
		map icons/iconw_bfg.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_grapple
{
	nopicmip
	{
		map icons/iconw_grapple.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_nailgun
{
	nopicmip
	{
		map icons/nailgun128.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_chaingun
{
	nopicmip
	{
		map icons/chaingun128.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconw_proxlauncher
{
	nopicmip
	{
		map icons/proxmine.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/weap_hmg
{
	nopicmip
	{
		map icons/weap_hmg.tga
		blendfunc blend
		alphaGen vertex
	}
}

//
// ammo icons
//

icons/icona_machinegun
{
	nopicmip
	{
		map icons/icona_machinegun.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/icona_rocket
{
	nopicmip
	{
		map icons/icona_rocket.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/icona_shotgun
{
	nopicmip
	{
		map icons/icona_shotgun.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/icona_grenade
{
	nopicmip
	{
		map icons/icona_grenade.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/icona_lightning
{
	nopicmip
	{
		map icons/icona_lightning.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/icona_plasma
{
	nopicmip
	{
		map icons/icona_plasma.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/icona_railgun
{
	nopicmip
	{
		map icons/icona_railgun.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/icona_bfg
{
	nopicmip
	{
		map icons/icona_bfg.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/icona_nailgun
{
	nopicmip
	{
		map icons/ammo_nailgun.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/icona_chaingun
{
	nopicmip
	{
		map icons/ammo_chaingun.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/icona_proxlauncher
{
	nopicmip
	{
		map icons/ammo_proxmine.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/ammo_hmg
{
	nopicmip
	{
		map icons/ammo_hmg.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/ammo_pack
{
	nopicmip
	{
		map icons/ammo_pack.tga
		blendfunc blend
		alphaGen vertex
	}
}


//
// armor icons
//

icons/iconr_shard
{
	nopicmip
	{
		map icons/iconr_shard.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconr_green
{
	nopicmip
	{
		map icons/iconr_green.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconr_yellow
{
	nopicmip
	{
		map icons/iconr_yellow.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconr_red
{
	nopicmip
	{
		map icons/iconr_red.tga
		blendfunc blend
		alphaGen vertex
	}
}

//
// health icons
//

icons/iconh_green
{
	nopicmip
	{
		map icons/iconh_green.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconh_yellow
{
	nopicmip
	{
		map icons/iconh_yellow.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconh_red
{
	nopicmip
	{
		map icons/iconh_red.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconh_mega
{
	nopicmip
	{
		map icons/iconh_mega.tga
		blendfunc blend
		alphaGen vertex
	}
}

//
// CTF icons
//

icons/iconf_red
{
	nopicmip
	{
		map icons/iconf_red.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/iconf_blu
{
	nopicmip
	{
		map icons/iconf_blu.tga
		blendfunc blend
		alphaGen vertex
	}
}

//
// Key icons
//
icons/key_gold
{
	nopicmip
	{
		map icons/key_gold.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/key_master
{
	nopicmip
	{
		map icons/key_master.tga
		blendfunc blend
		alphaGen vertex
	}
}

icons/key_silver
{
	nopicmip
	{
		map icons/key_silver.tga
		blendfunc blend
		alphaGen vertex
	}
}

//===================================================

gfx/2d/menuinfo
{
	nopicmip
	{
		map gfx/2d/menuinfo.tga
	}
}

gfx/2d/menuinfo2
{
	nopicmip
	{
		map gfx/2d/menuinfo2.tga
	}
}

gfx/2d/quit
{
	nopicmip
	nomipmaps
	{
		map gfx/2d/quit.tga
	}
}

gfx/2d/cursor
{
    nopicmip
	nomipmaps
    {
        map gfx/2d/cursor.tga
    }
}

gfx/misc/raindrop
{
	cull none
	polygonoffset
	nopicmip
	nomipmaps
	{
		map gfx/misc/raindrop.tga
		blendfunc blend
		//alphagen vertex
	}
}

gfx/misc/raindropwater
{
	cull none
	{
		map gfx/misc/raindropwater.tga
		blendfunc blend
		//alphagen vertex
	}
}

gfx/misc/raindropsolid
{
	polygonoffset
	{
		map gfx/misc/raindropsolid.tga
		blendfunc blend
		alphagen vertex
	}
}


gfx/misc/snow
{
	nopicmip
	cull none
	polygonoffset
	{
		map gfx/misc/snowflake.tga
		blendfunc blend
		alphagen vertex
	}
}

//==========================================================================

// chat icon floating over client's heads in the game

sprites/balloon3
{
	nopicmip
	{
		map sprites/balloon4.tga
		blendfunc blend
	}
}

// friend and foe icons floating over client's heads in teamplay games

sprites/friend
{
	nomipmaps
	nopicmip
	{
		map sprites/friend.tga
		blendfunc blend
		rgbgen vertex
	}
}
sprites/friend_armor
{
	nomipmaps
	nopicmip
	{
		map sprites/friend_armor.tga
		blendfunc blend
		rgbgen vertex
	}
}

sprites/friend_hit
{
	nomipmaps
	nopicmip
	{
		map sprites/friend_hit.tga
		blendfunc blend
	}
}

sprites/friend_dead
{
	nomipmaps
	nopicmip
	{
		map icons/icon_frag.tga
		blendfunc blend
	}
}

icons/icon_frag
{
	nomipmaps
	nopicmip
	{
		map icons/icon_frag.tga
		blendfunc blend
	}
}

sprites/trainer
{
	nomipmaps
	nopicmip
	{
		map sprites/trainer.tga
		blendfunc blend
		depthtest disable
	}
}

sprites/frozen
{
	nomipmaps
	nopicmip
	{
		map sprites/frozen.tga
		blendfunc blend
	}
}

sprites/flagcarrier
{
	nomipmaps
	nopicmip
	{
		map sprites/flagcarrier.tga
		blendfunc blend
		rgbgen vertex
	}
}

sprites/flagcarrier_hit
{
	nomipmaps
	nopicmip
	{
		map sprites/flagcarrier_hit.tga
		blendfunc blend
	}
}


sprites/neutralflagcarrier
{
	nomipmaps
	nopicmip
	{
		map sprites/flagcarrier_neutral.tga
		blendfunc	GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

sprites/dom_point
{
	nomipmaps
	nopicmip
	{
		map sprites/dompoint.tga
		blendfunc	GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

sprites/dom_point_distress
{
	nomipmaps
	nopicmip
	{
		map sprites/dompoint_distress.tga
		blendfunc	GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}


sprites/plasma1
{
	nopicmip
	cull disable
	{
		clampmap sprites/plasmaa.tga
		blendfunc add
		tcMod rotate 931
	}
}

sprites/plasma2
{
	nopicmip
	cull disable
	{
		map sprites/plasma2.tga
		blendfunc add
	}
}

// this is an example of a crossfaded animation cycle

textures/animationTest
{
	qer_editorimage	textures/liquids/bloodwater1.tga
	{
		animMap 0.5 textures/liquids/bloodwater1.tga textures/liquids/pool.tga textures/liquids/slime7.tga
	}	
	{
		animMap 0.5 textures/liquids/pool.tga textures/liquids/slime7.tga textures/liquids/bloodwater1.tga
		blendfunc	GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		alphaGen	wave sawtooth 0 1 0 0.5
	}	
	{
		map $lightmap
		blendfunc filter
	}
}

teleportEffect
{
	nopicmip
	cull none
	{
		map gfx/misc/teleportEffect2.tga
                blendfunc add
		rgbGen entity
		tcMod scale 1 4
		tcMod scroll 0 2
	}
}

// markShadow is the very cheap blurry blob underneat the player

markShadow
{
	nopicmip
	polygonOffset
	{
		map gfx/damage/shadow.tga
		blendfunc GL_ZERO GL_ONE_MINUS_SRC_COLOR
		rgbGen exactVertex
	}	
}

domShadow
{
	nopicmip
	novlcollapse
	polygonOffset
	{
		map gfx/2d/dom_point/dom_shadow.tga
		blendfunc blend
		rgbGen vertex
	}
	{
		clampmap gfx/2d/dom_point/dom_shadow_pulse_1.tga
		blendfunc blend
		tcMod stretch sin 1.0 .25 0 .4
		rgbGen vertex
	}	
	{
		clampmap gfx/2d/dom_point/dom_shadow_pulse_2.tga
		blendfunc blend
		tcMod stretch sin 1.0 .3 0 .4
		rgbGen vertex
	}
}

// projectionShadow is used for cheap squashed model shadows

projectionShadow
{
	nopicmip
	polygonOffset
	deformVertexes projectionShadow
	{
		map			*white
		blendfunc GL_ONE GL_ZERO
		rgbGen wave square 0 0 0 0				// just solid black
	}	
}


// wake is the mark on water surfaces for paddling players

wake
{
	nopicmip
	{
		clampmap sprites/splash.tga
		blendfunc add
		rgbGen vertex
                tcmod rotate 150
                tcMod stretch sin .9 0.08 0 0.8
		rgbGen wave sin .4 .1 .25 .5
	}
        {
		clampmap sprites/splash2.tga
		blendfunc add
		rgbGen vertex
                tcmod rotate 100
                tcMod stretch sin .9 0.05 0 0.9
		rgbGen wave sin .7 .3 .25 .4
	}

}


// viewBloodBlend gives the blended directional cue when you get hit

viewDamageBlend
{
	nopicmip
	sort	nearest
	{
		map gfx/damage/damage_screen.tga
		blendfunc blend
		rgbGen entity
		alphaGen vertex
	}
}

viewBloodBlend
{
	nopicmip
	sort	nearest
	{
		map dlc_gibs/blood_screen.tga
		blendfunc blend
		rgbGen entity
		alphaGen vertex
	}
}

waterBubble
{
	nopicmip
	sort	underwater
	cull none
	entityMergable		// allow all the sprites to be merged together
	{
		map sprites/bubble.tga
		blendfunc blend
		rgbGen		vertex
		alphaGen vertex
	}
}

gibspark
{
	nopicmip
	{
		map models/gibs/sphere.tga
		blendfunc add
	}
}

deathEffect
{
	nopicmip
	cull disable
	entityMergable		// allow all the sprites to be merged together
	{
		animmap 10 gfx/misc/deathSpike6.jpg gfx/misc/deathSpike7.jpg gfx/misc/deathSpike8.jpg gfx/misc/deathSpike9.jpg gfx/misc/deathSpike10.jpg gfx/misc/deathSpike11.jpg
		blendfunc add 
        rgbGen wave sawtooth .2 0.5 0 1
	}
	{
		animmap 10 gfx/misc/deathSpike7.jpg gfx/misc/deathSpike8.jpg gfx/misc/deathSpike9.jpg gfx/misc/deathSpike10.jpg gfx/misc/deathSpike11.jpg
		blendfunc add 
        rgbGen wave sawtooth .2 0.5 0 1
	}
	{
		clampmap gfx/misc/deathSpike12.jpg
		blendfunc add
        tcMod stretch triangle .4 0.05 0 6
        tcmod rotate 500
        rgbGen wave inversesawtooth 0 1 0 1.5
	}
	{
		clampmap models/powerups/pop2.tga
		blendfunc add
        tcMod stretch triangle .6 0.1 0 6
        tcmod rotate -300
        rgbGen wave inversesawtooth 0.4 0.2 0 1.5
	}
}
//alternate
//deathEffect
//{
//	nopicmip
//	cull disable
//	entityMergable
//	{
//	animmap 18 gfx/misc/death01.jpg gfx/misc/death02.jpg gfx/misc/death03.jpg gfx/misc/death04.jpg gfx/misc/death05.jpg gfx/misc/death04.jpg gfx/misc/death03.jpg gfx/misc/death02.jpg gfx/misc/death01.jpg
//		blendfunc add 
//        	rgbGen wave sawtooth .2 0.5 0 1
//	}
//	{
//	animmap 18 gfx/misc/death02.jpg gfx/misc/death03.jpg gfx/misc/death04.jpg gfx/misc/death05.jpg gfx/misc/death04.jpg gfx/misc/death03.jpg gfx/misc/death02.jpg gfx/misc/death01.jpg
//		blendfunc add 
//        	rgbGen wave sawtooth .2 0.5 0 1
//	}
//	{
//		clampmap models/powerups/pop2.tga
//		blendfunc add
//        	tcMod stretch triangle .6 0.1 0 6
//        	tcmod rotate -300
//        	rgbGen wave inversesawtooth 0.4 0.2 0 1.5
//	}
//}

smokePuff
{
	nopicmip
	cull none
	entityMergable		// allow all the sprites to be merged together
	{
		map gfx/misc/smokepuff3.tga
		blendfunc blend
		rgbGen		vertex
		alphaGen vertex
	}
}

hasteSmokePuff			// drops behind player's feet when speeded
{
	nopicmip
	cull none
	entityMergable		// allow all the sprites to be merged together
	{
		map gfx/misc/smokepuff3.tga
		blendfunc blend
        //blendfunc add
		rgbGen		vertex
		alphaGen vertex
	}
}

surfacePuff			// drops behind player's feet when speeded
{
	nopicmip
	cull none
	entityMergable		// allow all the sprites to be merged together
	{
		map gfx/misc/smokepuff2b.tga
		blendfunc blend
		rgbGen		vertex
		alphaGen vertex
	}
}

smokePuffRagePro
{
	nopicmip
	cull none
	entityMergable		// allow all the sprites to be merged together
	{
		map gfx/misc/smokepuffragepro.tga
		blendfunc blend
	}
}

shotgunSmokePuff
{
	nopicmip
	cull none
	{
		map gfx/misc/smokepuff2b.tga
		blendfunc blend
		alphaGen entity		
		rgbGen entity
	}
}

flareShader
{
	cull none
	{
		map gfx/misc/flare.tga
		blendfunc add
		rgbGen vertex
	}
}

sun
{
	cull none
	{
		map gfx/misc/sun.tga
		blendfunc add
		rgbGen vertex
	}
}

railDisc
{
	nopicmip
	sort nearest
	cull none
        deformVertexes wave 100 sin 0 .5 0 2.4
	{
		clampmap gfx/misc/raildisc_mono2.tga 
		blendfunc add
		rgbGen vertex
                 tcMod rotate -30
	}
}

railCore
{
	nopicmip
	sort nearest
	cull none
	{
		map gfx/misc/railcorethin_mono.tga
		blendfunc add
		rgbGen vertex
		tcMod scroll -1 0
	}
}

// shader used on the occasional machinegun bullet tracers

gfx/misc/tracer
{
	nopicmip
	cull none
	{
		map	gfx/misc/tracer2.tga
		blendfunc add
	}
}

// shader used on the occasional machinegun bullet tracers

gfx/misc/iceball
{
	nopicmip
	cull none
	{
		map	gfx/misc/iceball.tga
		blendfunc add
	}
}

//
// wall marks
// use blendfunc GL_ZERO GL_ONE_MINUS_SRC_COLOR so that
// their "contribution" can be damped down in fog volumes
// with distance

// begin gibs dlc

bloodSpray1			// this is the spurt of blood when a character gets hit
{
	polygonOffset
	sort 6    
	nopicmip			// make sure a border remains
	entityMergable		// allow all the sprites to be merged together
	{
		clampmap	dlc_gibs/bloodspray1.tga
		blendfunc	blend
		rgbGen		identityLighting
		alphaGen	vertex
	}
}

bloodSpray2			// this is the spurt of blood when a character gets hit
{
	polygonOffset
	sort 6  
	nopicmip			// make sure a border remains
	entityMergable		// allow all the sprites to be merged together
	{
		clampmap	dlc_gibs/bloodspray2.tga
		blendfunc	blend
		rgbGen		identityLighting
		alphaGen	vertex
	}
}


bloodSpray3			// this is the spurt of blood when a character gets hit
{
	polygonOffset
	sort 6
	nopicmip			// make sure a border remains
	entityMergable		// allow all the sprites to be merged together
	{
		clampmap	dlc_gibs/bloodspray3.tga
		blendfunc	blend
		rgbGen		identityLighting
		alphaGen	vertex
	}
}


bloodSpray4			// this is the spurt of blood when a character gets hit
{
	polygonOffset
	sort 6 
	nopicmip			// make sure a border remains
	entityMergable		// allow all the sprites to be merged together
	{
		clampmap	dlc_gibs/bloodspray4.tga
		blendfunc	blend
		rgbGen		identityLighting
		alphaGen	vertex
	}
}

// end gibs dlc

iceMark
{
	nopicmip			// make sure a border remains
	polygonOffset
	{
		clampmap gfx/damage/ice_stain.tga
		blendfunc blend
		rgbGen identityLighting
		alphaGen vertex
	}
}

iceTrail
{
        
	nopicmip			// make sure a border remains
	entityMergable		// allow all the sprites to be merged together
	{
        clampmap gfx/damage/ice_spurt.tga
		blendfunc blend
		rgbGen		vertex
		alphaGen vertex
	}
}

gfx/damage/bullet_mrk
{
	nopicmip
	polygonOffset
	{
		map gfx/damage/bullet_mrk.tga
		blendfunc GL_ZERO GL_ONE_MINUS_SRC_COLOR
		rgbGen exactVertex
	}
}

gfx/damage/burn_med_mrk
{
	nopicmip
	polygonOffset
	{
		map gfx/damage/burn_med_mrk.tga
		blendfunc GL_ZERO GL_ONE_MINUS_SRC_COLOR
		rgbGen exactVertex
	}
}

gfx/damage/hole_lg_mrk
{
	nopicmip
	polygonOffset
	{
		map gfx/damage/hole_lg_mrk.tga
		blendfunc GL_ZERO GL_ONE_MINUS_SRC_COLOR
		rgbGen exactVertex
	}
}

gfx/damage/plasma_mrk
{
	nopicmip
	polygonOffset
	{
		map gfx/damage/plasma_mrk.tga
		blendfunc blend
		rgbGen vertex
		alphaGen vertex
	}
}

gfx/damage/cracked_mrk
{
	nopicmip
	polygonOffset
	{
		map gfx/damage/cracked_mrk.tga
		blendfunc GL_ZERO GL_ONE_MINUS_SRC_COLOR
		rgbGen exactVertex
	}
}


//===============================================================

// scoreboard header tabs

scoreboardName
{
	nopicmip
	nomipmaps
	{
		clampmap menu/tab/name.tga
		blendfunc blend
	}
}

scoreboardScore
{
	nopicmip
	nomipmaps
	{
		clampmap menu/tab/score.tga
		blendfunc blend
	}
}

scoreboardTime
{
	nopicmip
	nomipmaps
	{
		clampmap menu/tab/time.tga
		blendfunc blend
	}
}

scoreboardPing
{
	nopicmip
	nomipmaps
	{
		clampmap menu/tab/ping.tga
		blendfunc blend
	}
}

//===============================================================

gfx/2d/crosshair1
{
	nopicmip
	{
		map gfx/2d/crosshair1.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair2
{
	nopicmip
	{
		map gfx/2d/crosshair2.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair3
{
	nopicmip
	{
		map gfx/2d/crosshair3.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair4
{
	nopicmip
	{
		map gfx/2d/crosshair4.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair5
{
	nopicmip
	{
		map gfx/2d/crosshair5.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair6
{
	nopicmip
	{
		map gfx/2d/crosshair6.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair7
{
	nopicmip
	{
		map gfx/2d/crosshair7.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair8
{
	nopicmip
	{
		map gfx/2d/crosshair8.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair9
{
	nopicmip
	{
		map gfx/2d/crosshair9.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair10
{
	nopicmip
	{
		map gfx/2d/crosshair10.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair11
{
	nopicmip
	{
		map gfx/2d/crosshair11.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair12
{
	nopicmip
	{
		map gfx/2d/crosshair12.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair13
{
	nopicmip
	{
		map gfx/2d/crosshair13.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair14
{
	nopicmip
	{
		map gfx/2d/crosshair14.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair15
{
	nopicmip
	{
		map gfx/2d/crosshair15.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair16
{
	nopicmip
	{
		map gfx/2d/crosshair16.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair17
{
	nopicmip
	{
		map gfx/2d/crosshair17.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair18
{
	nopicmip
	{
		map gfx/2d/crosshair18.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair19
{
	nopicmip
	{
		map gfx/2d/crosshair19.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair20
{
	nopicmip
	{
		map gfx/2d/crosshair20.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair21
{
	nopicmip
	{
		map gfx/2d/crosshair21.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair22
{
	nopicmip
	{
		map gfx/2d/crosshair22.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair23
{
	nopicmip
	{
		map gfx/2d/crosshair23.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair24
{
	nopicmip
	{
		map gfx/2d/crosshair24.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair25
{
	nopicmip
	{
		map gfx/2d/crosshair25.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair26
{
	nopicmip
	{
		map gfx/2d/crosshair26.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair27
{
	nopicmip
	{
		map gfx/2d/crosshair27.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair28
{
	nopicmip
	{
		map gfx/2d/crosshair28.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/crosshair29
{
	nopicmip
	{
		map gfx/2d/crosshair29.tga
		blendfunc blend
		rgbGen exactVertex
	}
}

gfx/2d/bigchars
{
	nopicmip
	nomipmaps
	{
		map gfx/2d/bigchars.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/select
{
	nopicmip
	{
		map gfx/2d/select.tga
		blendfunc blend
		rgbGen identity
		rgbgen vertex
	}
}

gfx/2d/assault1d
{
	nopicmip
	{
		map gfx/2d/assault1d.tga
		blendfunc blend
	}
}

gfx/2d/armor1h
{
	nopicmip
	{
		map gfx/2d/armor1h.tga
		blendfunc blend
	}
}

gfx/2d/health
{
	nopicmip
	{
		map gfx/2d/health.tga
		blendfunc blend
	}
}

gfx/2d/blank
{
	nopicmip
	{
		map gfx/2d/blank.tga
		blendfunc blend
	}
}

gfx/2d/numbers/zero_32b
{
	nopicmip
	{
		map gfx/2d/numbers/zero_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/one_32b
{
	nopicmip
	{
		map gfx/2d/numbers/one_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/two_32b
{
	nopicmip
	{
		map gfx/2d/numbers/two_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/three_32b
{
	nopicmip
	{
		map gfx/2d/numbers/three_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/four_32b
{
	nopicmip
	{
		map gfx/2d/numbers/four_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/five_32b
{
	nopicmip
	{
		map gfx/2d/numbers/five_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/six_32b
{
	nopicmip
	{
		map gfx/2d/numbers/six_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/seven_32b
{
	nopicmip
	{
		map gfx/2d/numbers/seven_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/eight_32b
{
	nopicmip
	{
		map gfx/2d/numbers/eight_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/nine_32b
{
	nopicmip
	{
		map gfx/2d/numbers/nine_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/minus_32b
{
	nopicmip
	{
		map gfx/2d/numbers/minus_32b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/zero_64b
{
	nopicmip
	{
		map gfx/2d/numbers/zero_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/one_64b
{
	nopicmip
	{
		map gfx/2d/numbers/one_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/two_64b
{
	nopicmip
	{
		map gfx/2d/numbers/two_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/three_64b
{
	nopicmip
	{
		map gfx/2d/numbers/three_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/four_64b
{
	nopicmip
	{
		map gfx/2d/numbers/four_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/five_64b
{
	nopicmip
	{
		map gfx/2d/numbers/five_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/six_64b
{
	nopicmip
	{
		map gfx/2d/numbers/six_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/seven_64b
{
	nopicmip
	{
		map gfx/2d/numbers/seven_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/eight_64b
{
	nopicmip
	{
		map gfx/2d/numbers/eight_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/nine_64b
{
	nopicmip
	{
		map gfx/2d/numbers/nine_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/numbers/minus_64b
{
	nopicmip
	{
		map gfx/2d/numbers/minus_64b.tga
		blendfunc blend
		rgbgen vertex
	}
}

icons/headshot
{
	nopicmip
	{
		map icons/headshot.tga
		blendfunc blend
		rgbgen vertex
	}
}

//
// weapon hits
// All of these will be put on entities with a shaderTime offset, so they
// can be expected to start at time 0 for each separate explosion
//
// Many of these are use smoothly morphed animating textures by pairing
// sawtooth and iverse sawtooth rgbGens

plasmaExplosion
{
	nopicmip
	cull disable
	{
		clampmap models/weaphits/plasmaboom.tga
		blendfunc add
                tcMod stretch triangle .6 0.1 0 8
                tcmod rotate 999
                rgbGen wave inversesawtooth 0 1 0 1.5
	}
}

railExplosion
{
	nopicmip
	cull disable
        {
		animmap 5 models/weaphits/ring02_1.tga  models/weaphits/ring02_2.tga  models/weaphits/ring02_3.tga models/weaphits/ring02_4.tga gfx/colors/black.tga
		alphaGen wave inversesawtooth 0 1 0 5
		blendfunc blend
	}
	{
		animmap 5 models/weaphits/ring02_2.tga  models/weaphits/ring02_3.tga models/weaphits/ring02_4.tga gfx/colors/black.tga gfx/colors/black.tga
		alphaGen wave sawtooth 0 1 0 5
		blendfunc blend
	}
}

lightningExplosion
{
	nopicmip
	cull disable
	{
		animmap 5 models/weaphits/ring02_1.tga  models/weaphits/ring02_3.tga  models/weaphits/ring02_3.tga gfx/colors/black.tga
		rgbGen wave inversesawtooth 0 1 0 5
		blendfunc add
	}
	{
		animmap 5 models/weaphits/ring02_2.tga  models/weaphits/ring02_3.tga  gfx/colors/black.tga gfx/colors/black.tga
		rgbGen wave sawtooth 0 1 0 5
		blendfunc add
	}
}

models/weaphits/bullet1
{
	nopicmip
	{
		map models/weaphits/bullet1.tga
	}
}

models/weaphits/bullet2
{
	nopicmip
	{
		map models/weaphits/bullet2.tga
	}
}

models/weaphits/bullet3
{
	nopicmip
	{
		map models/weaphits/bullet3.tga
	}
}

bulletExplosion
{
	nopicmip
	cull disable
	{
		animmap 5 models/weaphits/bullet1.tga  models/weaphits/bullet2.tga  models/weaphits/bullet3.tga gfx/colors/black.tga
		rgbGen wave inversesawtooth 0 1 0 5
		blendfunc add
	}
	{
		animmap 5 models/weaphits/bullet2.tga  models/weaphits/bullet3.tga  gfx/colors/black.tga gfx/colors/black.tga
		rgbGen wave sawtooth 0 1 0 5
		blendfunc add
	}
}

rocketExplosion
{
	nopicmip
	cull disable
	{
		animmap 8 models/weaphits/rlboom/rlboom_1.tga  models/weaphits/rlboom/rlboom_2.tga models/weaphits/rlboom/rlboom_3.tga models/weaphits/rlboom/rlboom_4.tga models/weaphits/rlboom/rlboom_5.tga models/weaphits/rlboom/rlboom_6.tga models/weaphits/rlboom/rlboom_7.tga models/weaphits/rlboom/rlboom_8.tga
		rgbGen wave inversesawtooth 0 1 0 8
		blendfunc add
	}
	{
		animmap 8 models/weaphits/rlboom/rlboom_2.tga models/weaphits/rlboom/rlboom_3.tga models/weaphits/rlboom/rlboom_4.tga models/weaphits/rlboom/rlboom_5.tga models/weaphits/rlboom/rlboom_6.tga models/weaphits/rlboom/rlboom_7.tga models/weaphits/rlboom/rlboom_8.tga gfx/colors/black.tga
		rgbGen wave sawtooth 0 1 0 8
		blendfunc add
	}
}

grenadeExplosion
{
	nopicmip
	cull disable
	{
		animmap 5 models/weaphits/glboom/glboom_1.tga  models/weaphits/glboom/glboom_2.tga models/weaphits/glboom/glboom_3.tga
		rgbGen wave inversesawtooth 0 1 0 5
		blendfunc add
	}
	{
		animmap 5 models/weaphits/glboom/glboom_2.tga  models/weaphits/glboom/glboom_3.tga gfx/colors/black.tga
		rgbGen wave sawtooth 0 1 0 5
		blendfunc add
	}
}

bfgExplosion
{
	nopicmip
	cull disable
	{
		animmap 5 models/weaphits/bfgboom/bfgboom_1.tga  models/weaphits/bfgboom/bfgboom_2.tga models/weaphits/bfgboom/bfgboom_3.tga
		rgbGen wave inversesawtooth 0 1 0 5
		blendfunc add
	}
	{
		animmap 5 models/weaphits/bfgboom/bfgboom_2.tga models/weaphits/bfgboom/bfgboom_3.tga gfx/colors/black.tga
		rgbGen wave sawtooth 0 1 0 5
		blendfunc add
	}
}

gfx/misc/jack-o-view
{
	nopicmip
	{ 
		map gfx/misc/jack-o-view.tga
		blendfunc blend
	}
}

gfx/misc/vignette
{
	nopicmip
	{ 
		map gfx/misc/vignette.tga
		blendfunc blend
	}
}

gfx/2d/unavailable
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/unavailable.tga
		blendfunc blend
		rgbgen vertex
	}
}

gfx/2d/quad_hog/quad
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/quad_hog/quad_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/quad_hog/quad.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/quad_hog/quadhog
{
	nopicmip
	{
		map gfx/2d/quad_hog/quadhog.tga
		blendfunc	GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

gfx/2d/infected/bite
{
	nomipmaps
	nopicmip
	{
		map gfx/2d/infected/bite.tga
		blendfunc	GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen vertex
	}
}

gfx/2d/infected/pg
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/infected/pg_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/infected/pg.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/powerup/quad
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/powerup/quad.tga
		blendfunc blend
		rgbgen vertex
		alphagen vertex
	}
}

gfx/2d/powerup/bs
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/powerup/bs.tga
		blendfunc blend
		rgbgen vertex
		alphagen vertex
	}
}

gfx/2d/powerup/invis
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/powerup/invis.tga
		blendfunc blend
		rgbgen vertex
		alphagen vertex
	}
}

gfx/2d/powerup/haste
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/powerup/haste.tga
		blendfunc blend
		rgbgen vertex
		alphagen vertex
	}
}

gfx/2d/powerup/regen
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/powerup/regen.tga
		blendfunc blend
		rgbgen vertex
		alphagen vertex
	}
}

gfx/2d/powerup/incoming
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/powerup/incoming.tga
		blendfunc blend
		rgbgen vertex
		alphagen vertex
		rgbGen wave sin 1 .5 0 1
	}
}

gfx/2d/har/poi_capture
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/har/capture_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/har/capture.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/ad/poi_attack
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/ad/attack_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/ad/attack.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/ad/poi_capture
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/ad/capture_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/ad/capture.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/ad/poi_defend
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/ad/defend_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/ad/defend.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_cap_a
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/dom_point/dom_cap_a_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_cap_a.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_cap_a_dist
{
	nopicmip
	novlcollapse
	{
		AnimMap 4 gfx/2d/dom_point/dom_cap_a_tint.tga gfx/2d/dom_point/dom_distress.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_cap_a.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_cap_b
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/dom_point/dom_cap_b_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_cap_b.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_cap_b_dist
{
	nopicmip
	novlcollapse
	{
		AnimMap 4 gfx/2d/dom_point/dom_cap_b_tint.tga gfx/2d/dom_point/dom_distress.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_cap_b.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_cap_c
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/dom_point/dom_cap_c_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_cap_c.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_cap_c_dist
{
	nopicmip
	novlcollapse
	{
		AnimMap 4 gfx/2d/dom_point/dom_cap_c_tint.tga gfx/2d/dom_point/dom_distress.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_cap_c.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_cap_d
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/dom_point/dom_cap_d_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_cap_d.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_cap_d_dist
{
	nopicmip
	novlcollapse
	{
		AnimMap 4 gfx/2d/dom_point/dom_cap_d_tint.tga gfx/2d/dom_point/dom_distress.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_cap_d.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_cap_e
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/dom_point/dom_cap_e_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_cap_e.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_cap_e_dist
{
	nopicmip
	novlcollapse
	{
		AnimMap 4 gfx/2d/dom_point/dom_cap_e_tint.tga gfx/2d/dom_point/dom_distress.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_cap_e.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_def_a
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/dom_point/dom_def_a_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_def_a.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_def_a_dist
{
	nopicmip
	novlcollapse
	{
		AnimMap 4 gfx/2d/dom_point/dom_def_a_tint.tga gfx/2d/dom_point/dom_distress.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_def_a.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_def_b
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/dom_point/dom_def_b_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_def_b.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_def_b_dist
{
	nopicmip
	novlcollapse
	{
		AnimMap 4 gfx/2d/dom_point/dom_def_b_tint.tga gfx/2d/dom_point/dom_distress.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_def_b.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_def_c
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/dom_point/dom_def_c_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_def_c.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_def_c_dist
{
	nopicmip
	novlcollapse
	{
		AnimMap 4 gfx/2d/dom_point/dom_def_c_tint.tga gfx/2d/dom_point/dom_distress.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_def_c.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_def_d
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/dom_point/dom_def_d_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_def_d.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_def_d_dist
{
	nopicmip
	novlcollapse
	{
		AnimMap 4 gfx/2d/dom_point/dom_def_d_tint.tga gfx/2d/dom_point/dom_distress.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_def_d.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_def_e
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/dom_point/dom_def_e_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_def_e.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/dom_point/dom_def_e_dist
{
	nopicmip
	novlcollapse
	{
		AnimMap 4 gfx/2d/dom_point/dom_def_e_tint.tga gfx/2d/dom_point/dom_distress.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/dom_point/dom_def_e.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/race/start
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/race/race_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/race/start.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/race/checkpoint
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/race/race_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/race/checkpoint.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/2d/race/finish
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/race/race_tint.tga
		blendfunc add
		rgbgen vertex
	}
	{
		map gfx/2d/race/finish.tga
		blendfunc blend
		rgbgen identity
	}
}

gfx/misc/racenav
{
	nopicmip
	novlcollapse
	cull disable
	{
		map gfx/misc/navray.tga
		blendfunc add
        tcMod scroll .75  0
	}
}

gfx/2d/timer/armor
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/armor.tga
		blendfunc blend
		rgbgen vertex
		alphaGen vertex
	}
}

gfx/2d/timer/bs
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/bs.tga
		blendfunc blend
		rgbgen vertex
		alphaGen vertex
	}
}

gfx/2d/timer/haste
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/haste.tga
		blendfunc blend
		rgbgen vertex
		alphaGen vertex
	}
}

gfx/2d/timer/health
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/health.tga
		blendfunc blend
		rgbgen vertex
		alphaGen vertex
	}
}

gfx/2d/timer/invis
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/invis.tga
		blendfunc blend
		rgbgen vertex
		alphaGen vertex
	}
}

gfx/2d/timer/medkit
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/medkit.tga
		blendfunc blend
		rgbgen vertex
		alphaGen vertex
	}
}

gfx/2d/timer/slice5
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/slice_5.tga
		blendfunc blend
		alphaGen vertex
	}
}

gfx/2d/timer/slice5_current
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/slice_5.tga
		blendfunc blend
		rgbGen wave sin 1 .5 0 1		
		alphaGen vertex
	}
}

gfx/2d/timer/slice7
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/slice_7.tga
		blendfunc blend
		alphaGen vertex
	}
}

gfx/2d/timer/slice7_current
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/slice_7.tga
		blendfunc blend
		rgbGen wave sin 1 .5 0 1
		alphaGen vertex
	}
}

gfx/2d/timer/slice12
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/slice_12.tga
		blendfunc blend
		alphaGen vertex
	}
}

gfx/2d/timer/slice12_current
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/slice_12.tga
		blendfunc blend
		rgbGen wave sin 1 .5 0 1
		alphaGen vertex
	}
}

gfx/2d/timer/slice24
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/slice_24.tga
		blendfunc blend
		alphaGen vertex
	}
}

gfx/2d/timer/slice24_current
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/slice_24.tga
		blendfunc blend
		rgbGen wave sin 1 .5 0 1
		alphaGen vertex
	}
}

gfx/2d/timer/quad
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/quad.tga
		blendfunc blend
		rgbgen vertex
		alphaGen vertex
	}
}

gfx/2d/timer/regen
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/regen.tga
		blendfunc blend
		rgbgen vertex
		alphaGen vertex
	}
}

gfx/2d/timer/unknown
{
	nopicmip
	novlcollapse
	{
		map gfx/2d/timer/unknown.tga
		blendfunc blend
		rgbgen vertex
		alphaGen vertex
	}
}

