# Export a full Ghidra C-language source recreation for the Quake Live UI module.
#@author QuakeLive-reverse
#@category QuakeLive/UI
#@menupath Tools.QuakeLive.Export UI Source Recreation
#@toolbar

"""Decompile every function in uix86.dll and write a structured C source recreation.

Run *after* ``ApplyUISymbolMap.py`` so that function names reflect the committed
symbol map before the C output is generated.

Output layout under ``<output_root>/``::

    <output_root>/
        ui_reconstruction.c   -- full annotated decompile, all functions
        include/
            ui_ghidra_reference.h -- copied committed reference header
            ui_prototypes.h   -- forward declarations for all decompiled functions

Run via the Ghidra GUI or headless::

    analyzeHeadless <project_dir> <project_name> \
        -process uix86.dll \
        -postScript ExportUISourceRecreation.py \
        [<output_root>] [<reference_path>]

``<output_root>`` defaults to
``<repo_root>/references/reverse-engineering/ghidra/uix86/source-recreation``.
``<reference_path>`` defaults to
``<repo_root>/references/reverse-engineering/ghidra/uix86/ui_ghidra_reference.h``.
The script resolves ``<repo_root>`` relative to its own location
(``<repo_root>/ghidra_scripts/``).
"""

import os
import shutil

from ghidra.app.decompiler import DecompInterface


_HEADER = """\
/*
 * Quake Live UI Module — Ghidra C-language source recreation
 *
 * Binary  : uix86.dll
 * Source  : Ghidra decompiler output with committed symbol-map annotations
 *           applied via ghidra_scripts/ApplyUISymbolMap.py
 *
 * This file is machine-assisted output from the Ghidra decompiler.  It is
 * intended as a reverse-engineering reference, not a drop-in replacement.
 * Treat it as a hint set alongside the Binary Ninja HLIL dumps in
 *   references/hlil/quakelive/uix86.all/
 * and the companion Ghidra corpus in
 *   references/reverse-engineering/ghidra/uix86/
 *
 * Do NOT edit this file by hand — regenerate it by running:
 *   ApplyUISymbolMap.py  (rename pass)
 *   ExportUISourceRecreation.py  (export pass)
 */

#include "include/ui_ghidra_reference.h"
#include "include/ui_prototypes.h"

"""

_PROTO_HEADER = """\
/*
 * Quake Live UI Module — function forward declarations
 *
 * Auto-generated by ghidra_scripts/ExportUISourceRecreation.py
 * Do NOT edit by hand — regenerate from Ghidra.
 */

#ifndef UI_PROTOTYPES_H
#define UI_PROTOTYPES_H

"""

_PROTO_FOOTER = "\n#endif /* UI_PROTOTYPES_H */\n"


def _ensure_dir(path):
	if not os.path.isdir(path):
		os.makedirs(path)


def _write(path, text):
	with open(path, "w") as fh:
		fh.write(text)


def main():
	program = currentProgram
	if program is None:
		printerr("No program is active; aborting")
		return

	script_dir = os.path.dirname(os.path.abspath(str(sourceFile)))
	repo_root = os.path.dirname(script_dir)
	default_out = os.path.join(
		repo_root,
		"references",
		"reverse-engineering",
		"ghidra",
		"uix86",
		"source-recreation",
	)
	default_reference = os.path.join(
		repo_root,
		"references",
		"reverse-engineering",
		"ghidra",
		"uix86",
		"ui_ghidra_reference.h",
	)

	args = list(getScriptArgs())
	output_root = args[0] if args else default_out
	reference_path = args[1] if len(args) > 1 else default_reference

	recon_dir = output_root
	include_dir = os.path.join(output_root, "include")
	_ensure_dir(recon_dir)
	_ensure_dir(include_dir)

	if not os.path.isfile(reference_path):
		printerr("Reference header not found: %s" % reference_path)
		return

	shutil.copyfile(
		reference_path,
		os.path.join(include_dir, "ui_ghidra_reference.h")
	)

	func_manager = program.getFunctionManager()

	funcs = []
	func_iter = func_manager.getFunctions(True)
	while func_iter.hasNext():
		func = func_iter.next()
		if not func.isExternal():
			funcs.append(func)
	funcs.sort(key=lambda f: f.getEntryPoint().getOffset())

	println("ExportUISourceRecreation: decompiling %d functions..." % len(funcs))

	decompiler = DecompInterface()
	decompiler.openProgram(program)

	recon_lines = [_HEADER]
	proto_lines = [_PROTO_HEADER]
	succeeded = 0
	failed = 0

	try:
		for func in funcs:
			if monitor.isCancelled():
				break

			name = func.getName()
			addr = func.getEntryPoint()
			size = func.getBody().getNumAddresses()

			recon_lines.append("/* %s @ %s  size %d */" % (name, addr, size))

			results = decompiler.decompileFunction(func, 90, monitor)
			if results is None or not results.decompileCompleted() or results.getDecompiledFunction() is None:
				recon_lines.append("/* decompile failed */\n")
				failed += 1
				continue

			c_code = results.getDecompiledFunction().getC()
			recon_lines.append(c_code)
			recon_lines.append("")
			succeeded += 1

			proto = results.getDecompiledFunction().getSignature()
			if proto:
				proto_lines.append("%s;" % proto)
	finally:
		decompiler.dispose()

	_write(
		os.path.join(recon_dir, "ui_reconstruction.c"),
		"\n".join(recon_lines)
	)

	proto_lines.append(_PROTO_FOOTER)
	_write(
		os.path.join(include_dir, "ui_prototypes.h"),
		"\n".join(proto_lines)
	)

	println(
		"ExportUISourceRecreation: succeeded=%d failed=%d -> %s"
		% (succeeded, failed, output_root)
	)


main()
