# Export a full Ghidra C++-style source recreation for quakelive_steam.exe.
#@author QuakeLive-reverse
#@category QuakeLive/Host
#@menupath Tools.QuakeLive.Export quakelive_steam Source Recreation
#@toolbar

"""Decompile every non-external function in quakelive_steam.exe.

The output layout under ``<output_root>/`` is:

    <output_root>/
        quakelive_steam_decomp.cpp
        quakelive_steam_manifest.json
        include/
            quakelive_steam_ghidra_compat.hpp
            quakelive_steam_prototypes.hpp

Run after ``ApplyQuakeLiveSteamMappings.py`` so the generated C output reflects
the committed alias corpus and analysis labels.
"""

import json
import os

from ghidra.app.decompiler import DecompInterface


_CPP_HEADER = """\
/*
 * Quake Live retail Windows host -- Ghidra source recreation
 *
 * Binary  : quakelive_steam.exe
 * Source  : full-function Ghidra decompiler export after committed symbol and
 *           analysis-label application
 *
 * This file is machine-generated reverse-engineering reference material. It is
 * not intended to compile as-is and should not be edited by hand.
 *
 * Regenerate with:
 *   ApplyQuakeLiveSteamMappings.py
 *   ExportQuakeLiveSteamSourceRecreation.py
 */

#include "include/quakelive_steam_ghidra_compat.hpp"
#include "include/quakelive_steam_prototypes.hpp"

"""

_COMPAT_HEADER = """\
/*
 * Quake Live retail Windows host -- Ghidra compatibility header
 *
 * Auto-generated by ExportQuakeLiveSteamSourceRecreation.py.
 * This header provides lightweight compatibility aliases for common Ghidra
 * placeholder types so the generated export reads more like conventional C++.
 */

#pragma once

#include <cstddef>
#include <cstdint>

#ifndef __cdecl
#define __cdecl
#endif

#ifndef __fastcall
#define __fastcall
#endif

#ifndef __stdcall
#define __stdcall
#endif

#ifndef __thiscall
#define __thiscall
#endif

using undefined = std::uint8_t;
using undefined1 = std::uint8_t;
using undefined2 = std::uint16_t;
using undefined4 = std::uint32_t;
using undefined8 = std::uint64_t;
using uchar = std::uint8_t;
using ushort = std::uint16_t;
using uint = std::uint32_t;
using ulong = std::uint32_t;
using longlong = std::int64_t;
using ulonglong = std::uint64_t;
using wchar16 = std::uint16_t;
using byte = std::uint8_t;
using float10 = long double;
using code = void;

"""

_PROTO_HEADER = """\
/*
 * Quake Live retail Windows host -- forward declarations
 *
 * Auto-generated by ExportQuakeLiveSteamSourceRecreation.py.
 * Refined signatures may be substituted later by the post-process step.
 */

#pragma once

"""


def _ensure_dir(path):
	if not os.path.isdir(path):
		os.makedirs(path)


def _write(path, text):
	with open(path, "w") as handle:
		handle.write(text)


def _format_address(address):
	return "0x%08X" % address.getOffset()


def main():
	program = currentProgram
	if program is None:
		printerr("No program is active; aborting")
		return

	script_dir = os.path.dirname(os.path.abspath(str(sourceFile)))
	repo_root = os.path.dirname(script_dir)
	default_out = os.path.join(
		repo_root,
		"src2",
		"ghidra",
		"quakelive_steam_srp",
	)

	args = list(getScriptArgs())
	output_root = args[0] if args else default_out
	include_dir = os.path.join(output_root, "include")
	_ensure_dir(output_root)
	_ensure_dir(include_dir)

	func_manager = program.getFunctionManager()
	funcs = []
	func_iter = func_manager.getFunctions(True)
	while func_iter.hasNext():
		func = func_iter.next()
		if not func.isExternal():
			funcs.append(func)
	funcs.sort(key=lambda item: item.getEntryPoint().getOffset())

	println("ExportQuakeLiveSteamSourceRecreation: decompiling %d functions..." % len(funcs))

	decompiler = DecompInterface()
	decompiler.openProgram(program)

	recon_lines = [_CPP_HEADER]
	proto_lines = [_PROTO_HEADER]
	succeeded = 0
	failed = 0
	prototype_count = 0

	try:
		for func in funcs:
			if monitor.isCancelled():
				break

			name = func.getName()
			addr = func.getEntryPoint()
			size = func.getBody().getNumAddresses()
			recon_lines.append("/* %s @ %s size %d */" % (name, _format_address(addr), size))

			results = decompiler.decompileFunction(func, 90, monitor)
			if results is None or not results.decompileCompleted() or results.getDecompiledFunction() is None:
				recon_lines.append("/* decompile failed */")
				recon_lines.append("")
				failed += 1
				continue

			decompiled = results.getDecompiledFunction()
			recon_lines.append(decompiled.getC())
			recon_lines.append("")
			succeeded += 1

			signature = decompiled.getSignature()
			if signature:
				signature = signature.rstrip(";")
				proto_lines.append("%s;" % signature)
				prototype_count += 1
	finally:
		decompiler.dispose()

	_write(os.path.join(output_root, "quakelive_steam_decomp.cpp"), "\n".join(recon_lines))
	_write(os.path.join(include_dir, "quakelive_steam_ghidra_compat.hpp"), _COMPAT_HEADER)
	_write(os.path.join(include_dir, "quakelive_steam_prototypes.hpp"), "\n".join(proto_lines) + "\n")

	manifest = {
		"binary": os.path.basename(program.getExecutablePath()) or "quakelive_steam.exe",
		"input_path": program.getExecutablePath(),
		"output_root": output_root,
		"function_count": len(funcs),
		"decompile_succeeded": succeeded,
		"decompile_failed": failed,
		"prototype_count": prototype_count,
	}
	_write(os.path.join(output_root, "quakelive_steam_manifest.json"), json.dumps(manifest, indent=2, sort_keys=True))

	println(
		"ExportQuakeLiveSteamSourceRecreation: succeeded=%d failed=%d prototypes=%d -> %s"
		% (succeeded, failed, prototype_count, output_root)
	)


main()
